name: Terraform Apply

on:
  push:
    branches:
      - main
      - feature/phase2-cicd-security

permissions:
  id-token: write
  contents: read      

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          role-to-assume: ${{ vars.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Verify EKS Access
        run: |
          aws eks describe-cluster \
            --name project-bedrock-cluster \
            --region us-east-1

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name project-bedrock-cluster \
            --region us-east-1 \
            --role-arn ${{ vars.AWS_DEPLOYMENT_ROLE_ARN }}

      - name: Verify Kubernetes Access
        run: |
          kubectl get nodes

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan